name: dart_sort
description: A script for sorting tv shows and movies
version: 1.0.0
homepage:
author: Ryan Knell
author_email: ryan.knell@gmail.com
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies: